abs-path	:= arch/xmega

src-y		+= $(abs-path)/clksys.c
src-y		+= $(abs-path)/console.c
src-y		+= $(abs-path)/gpio.c
src-y		+= $(abs-path)/kos.c
src-y		+= $(abs-path)/hwtimer.c
src-y		+= $(abs-path)/usart.c
